# Document retrieval from Wikipedia data

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
people =pd.read_csv('~/ML-Specialization/Machine Learning Foundations: A Case Study Approach/Week 4/Dataset/people_wiki.csv')

In [3]:
people

,name,text
0,Digby Morrell,digby morrell born 10 october 1979 is a former...
1,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...
2,Harpdog Brown,harpdog brown is a singer and harmonica player...
3,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...
4,G-Enka,henry krvits born 30 december 1974 in tallinn ...
...,...,...
59066,Olari Elts,olari elts born april 27 1971 in tallinn eston...
59067,Scott F. Crago,scott francis crago born july 26 1963 twin bro...
59068,David Cass (footballer),david william royce cass born 27 march 1962 in...
59069,Keith Elias,keith hector elias born february 3 1972 in lac...
59070,Fawaz Damrah,fawaz mohammed damrah arabic fawwz damra was t...

# Explore data

## Taking a look at the entry for President Obama

In [4]:
obama = people[people['name'] == 'Barack Obama']

In [5]:
obama

               name                                               text
35817  Barack Obama  barack hussein obama ii brk husen bm born augu...

In [6]:
obama['text']

35817    barack hussein obama ii brk husen bm born augu...
Name: text, dtype: object

## Explore the entry for actor George Clooney

In [7]:
clooney = people[people['name'] == 'George Clooney']
clooney['text']

38514    george timothy clooney born may 6 1961 is an a...
Name: text, dtype: object

# Word counts for Obama acticle

In [8]:
from collections import Counter

In [9]:
res = obama['text'].str.split().apply(pd.value_counts)

In [10]:
res

,the,in,and,of,to,his,obama,act,a,he,...,street,relations,romney,equality,budget,tax,inaugurated,down,representing,cuba
35817,40,30,21,18,14,11,9,8,7,7,...,1,1,1,1,1,1,1,1,1,1

In [11]:
res = [Counter(x) for x in obama['text'].str.split()]

In [12]:
list(res)

[Counter({'barack': 1,
          'hussein': 1,
          'obama': 9,
          'ii': 1,
          'brk': 1,
          'husen': 1,
          'bm': 1,
          'born': 2,
          'august': 1,
          '4': 1,
          '1961': 1,
          'is': 2,
          'the': 40,
          '44th': 1,
          'and': 21,
          'current': 1,
          'president': 4,
          'of': 18,
          'united': 3,
          'states': 3,
          'first': 3,
          'african': 1,
          'american': 3,
          'to': 14,
          'hold': 1,
          'office': 2,
          'in': 30,
          'honolulu': 1,
          'hawaii': 1,
          'a': 7,
          'graduate': 1,
          'columbia': 1,
          'university': 2,
          'harvard': 2,
          'law': 6,
          'school': 3,
          'where': 1,
          'he': 7,
          'served': 2,
          'as': 6,
          'review': 1,
          'was': 5,
          'community': 1,
          'organizer': 1,
          'chicago': 2,
          'before': 1,
          'earning': 1,
          'his': 11,
          'degree': 1,
          'worked': 1,
          'civil': 1,
          'rights': 1,
          'attorney': 1,
          'taught': 1,
          'constitutional': 1,
          'at': 2,
          'from': 3,
          '1992': 1,
          '2004': 3,
          'three': 1,
          'terms': 1,
          'representing': 1,
          '13th': 1,
          'district': 1,
          'illinois': 2,
          'senate': 3,
          '1997': 1,
          'running': 1,
          'unsuccessfully': 1,
          'for': 4,
          'house': 2,
          'representatives': 2,
          '2000in': 1,
          'received': 1,
          'national': 2,
          'attention': 1,
          'during': 2,
          'campaign': 3,
          'represent': 1,
          'with': 3,
          'victory': 1,
          'march': 1,
          'democratic': 4,
          'party': 3,
          'primary': 2,
          'keynote': 1,
          'address': 1,
          'convention': 1,
          'july': 1,
          'election': 3,
          'november': 2,
          'began': 1,
          'presidential': 2,
          '2007': 1,
          'after': 4,
          'close': 1,
          'against': 1,
          'hillary': 1,
          'rodham': 1,
          'clinton': 1,
          '2008': 1,
          'won': 1,
          'sufficient': 1,
          'delegates': 1,
          'primaries': 1,
          'receive': 1,
          'nomination': 1,
          'then': 1,
          'defeated': 1,
          'republican': 2,
          'nominee': 2,
          'john': 1,
          'mccain': 1,
          'general': 1,
          'inaugurated': 1,
          'on': 2,
          'january': 3,
          '20': 2,
          '2009': 3,
          'nine': 1,
          'months': 1,
          'named': 1,
          'nobel': 1,
          'peace': 1,
          'prize': 1,
          'laureateduring': 1,
          'two': 1,
          'years': 1,
          'signed': 3,
          'into': 1,
          'economic': 1,
          'stimulus': 1,
          'legislation': 1,
          'response': 3,
          'great': 1,
          'recession': 1,
          'form': 1,
          'recovery': 1,
          'reinvestment': 1,
          'act': 8,
          'tax': 1,
          'relief': 2,
          'unemployment': 1,
          'insurance': 1,
          'reauthorization': 1,
          'job': 1,
          'creation': 1,
          '2010': 2,
          'other': 1,
          'major': 1,
          'domestic': 2,
          'initiatives': 1,
          'term': 3,
          'included': 1,
          'patient': 1,
          'protection': 2,
          'affordable': 1,
          'care': 1,
          'often': 1,
          'referred': 1,
          'obamacare': 1,
          'doddfrank': 1,
          'wall': 1,
          'street': 1,
          'reform': 1,
          'consumer': 1,
          'dont': 2,
          'ask': 1,
          'tell': 1,
          'repeal': 1,
          'foreign': 2,
          'policy': 2,
          'ended': 1,
          'us': 6,
          'military': 4,
          'involvement': 3,
          'iraq': 4,
          'war': 1,
          'increased': 1,
          'troop': 1,
          'levels': 1,
          'afghanistan': 2,
          'new': 1,
          'start': 1,
          'arms': 1,
          'control': 4,
          'treaty': 1,
          'russia': 1,
          'ordered': 3,
          'libya': 1,
          'operation': 1,
          'that': 1,
          'resulted': 1,
          'death': 1,
          'osama': 1,
          'bin': 1,
          'laden': 1,
          '2011': 3,
          'republicans': 1,
          'regained': 1,
          'lost': 1,
          'total': 1,
          '63': 1,
          'seats': 1,
          'lengthy': 1,
          'debate': 1,
          'over': 1,
          'federal': 1,
          'spending': 1,
          'whether': 1,
          'or': 1,
          'not': 1,
          'raise': 1,
          'nations': 1,
          'debt': 1,
          'limit': 1,
          'budget': 1,
          'taxpayer': 1,
          '2012obama': 1,
          'reelected': 1,
          '2012': 1,
          'defeating': 1,
          'mitt': 1,
          'romney': 1,
          'sworn': 1,
          'second': 2,
          '2013': 1,
          'has': 4,
          'promoted': 1,
          'policies': 1,
          'related': 1,
          'gun': 1,
          'sandy': 1,
          'hook': 1,
          'elementary': 1,
          'shooting': 1,
          'called': 1,
          'full': 1,
          'equality': 1,
          'lgbt': 1,
          'americans': 1,
          'while': 1,
          'administration': 1,
          'filed': 1,
          'briefs': 1,
          'which': 1,
          'urged': 1,
          'supreme': 1,
          'court': 1,
          'strike': 1,
          'down': 1,
          'defense': 1,
          'marriage': 1,
          '1996': 1,
          'californias': 1,
          'proposition': 1,
          '8': 1,
          'unconstitutional': 1,
          'gains': 1,
          'made': 1,
          'by': 1,
          'islamic': 1,
          'state': 1,
          'withdrawal': 1,
          'continued': 1,
          'process': 1,
          'ending': 1,
          'combat': 1,
          'operations': 1,
          'sought': 1,
          'normalize': 1,
          'relations': 1,
          'cuba': 1})]

In [13]:
obama['word_count']= [Counter(x) for x in obama['text'].str.split()]

/home/dipesh/anaconda3/envs/venv/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [14]:
obama

,name,text,word_count
35817,Barack Obama,barack hussein obama ii brk husen bm born augu...,"{'barack': 1, 'hussein': 1, 'obama': 9, 'ii': ..."

## Find most common words in Obama article

In [15]:
obama['word_count']

35817    {'barack': 1, 'hussein': 1, 'obama': 9, 'ii': ...
Name: word_count, dtype: object

In [16]:
rslt = pd.DataFrame(Counter(" ".join(obama['text']).split()).most_common(),columns=['Word', 'Frequency'])

In [17]:
rslt.style

In [18]:
obama_text = people.loc[people['name']=='Barack Obama', 'text'].tolist()

In [19]:
obama_text

['barack hussein obama ii brk husen bm born august 4 1961 is the 44th and current president of the united states and the first african american to hold the office born in honolulu hawaii obama is a graduate of columbia university and harvard law school where he served as president of the harvard law review he was a community organizer in chicago before earning his law degree he worked as a civil rights attorney and taught constitutional law at the university of chicago law school from 1992 to 2004 he served three terms representing the 13th district in the illinois senate from 1997 to 2004 running unsuccessfully for the united states house of representatives in 2000in 2004 obama received national attention during his campaign to represent illinois in the united states senate with his victory in the march democratic party primary his keynote address at the democratic national convention in july and his election to the senate in november he began his presidential campaign in 2007 and after a close primary campaign against hillary rodham clinton in 2008 he won sufficient delegates in the democratic party primaries to receive the presidential nomination he then defeated republican nominee john mccain in the general election and was inaugurated as president on january 20 2009 nine months after his election obama was named the 2009 nobel peace prize laureateduring his first two years in office obama signed into law economic stimulus legislation in response to the great recession in the form of the american recovery and reinvestment act of 2009 and the tax relief unemployment insurance reauthorization and job creation act of 2010 other major domestic initiatives in his first term included the patient protection and affordable care act often referred to as obamacare the doddfrank wall street reform and consumer protection act and the dont ask dont tell repeal act of 2010 in foreign policy obama ended us military involvement in the iraq war increased us troop levels in afghanistan signed the new start arms control treaty with russia ordered us military involvement in libya and ordered the military operation that resulted in the death of osama bin laden in january 2011 the republicans regained control of the house of representatives as the democratic party lost a total of 63 seats and after a lengthy debate over federal spending and whether or not to raise the nations debt limit obama signed the budget control act of 2011 and the american taxpayer relief act of 2012obama was reelected president in november 2012 defeating republican nominee mitt romney and was sworn in for a second term on january 20 2013 during his second term obama has promoted domestic policies related to gun control in response to the sandy hook elementary school shooting and has called for full equality for lgbt americans while his administration has filed briefs which urged the supreme court to strike down the defense of marriage act of 1996 and californias proposition 8 as unconstitutional in foreign policy obama ordered us military involvement in iraq in response to gains made by the islamic state in iraq after the 2011 withdrawal from iraq continued the process of ending us combat operations in afghanistan and has sought to normalize us relations with cuba']

In [20]:
from sklearn.feature_extraction.text import CountVectorizer
counter1 = CountVectorizer(stop_words='english')
counter1

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [21]:
count_matrix =counter1.fit_transform(obama_text)
count_matrix

<1x229 sparse matrix of type '<class 'numpy.int64'>'
	with 229 stored elements in Compressed Sparse Row format>

In [22]:
features = counter1.get_feature_names()
features

['13th',
 '1961',
 '1992',
 '1996',
 '1997',
 '20',
 '2000in',
 '2004',
 '2007',
 '2008',
 '2009',
 '2010',
 '2011',
 '2012',
 '2012obama',
 '2013',
 '44th',
 '63',
 'act',
 'address',
 'administration',
 'affordable',
 'afghanistan',
 'african',
 'american',
 'americans',
 'arms',
 'ask',
 'attention',
 'attorney',
 'august',
 'barack',
 'began',
 'bin',
 'bm',
 'born',
 'briefs',
 'brk',
 'budget',
 'californias',
 'called',
 'campaign',
 'care',
 'chicago',
 'civil',
 'clinton',
 'close',
 'columbia',
 'combat',
 'community',
 'constitutional',
 'consumer',
 'continued',
 'control',
 'convention',
 'court',
 'creation',
 'cuba',
 'current',
 'death',
 'debate',
 'debt',
 'defeated',
 'defeating',
 'defense',
 'degree',
 'delegates',
 'democratic',
 'district',
 'doddfrank',
 'domestic',
 'dont',
 'earning',
 'economic',
 'election',
 'elementary',
 'ended',
 'ending',
 'equality',
 'federal',
 'filed',
 'foreign',
 'form',
 'gains',
 'general',
 'graduate',
 'great',
 'gun',
 'harvard',
 'hawaii',
 'hillary',
 'hold',
 'honolulu',
 'hook',
 'house',
 'husen',
 'hussein',
 'ii',
 'illinois',
 'inaugurated',
 'included',
 'increased',
 'initiatives',
 'insurance',
 'involvement',
 'iraq',
 'islamic',
 'january',
 'job',
 'john',
 'july',
 'keynote',
 'laden',
 'laureateduring',
 'law',
 'legislation',
 'lengthy',
 'levels',
 'lgbt',
 'libya',
 'limit',
 'lost',
 'major',
 'march',
 'marriage',
 'mccain',
 'military',
 'mitt',
 'months',
 'named',
 'national',
 'nations',
 'new',
 'nobel',
 'nomination',
 'nominee',
 'normalize',
 'november',
 'obama',
 'obamacare',
 'office',
 'operation',
 'operations',
 'ordered',
 'organizer',
 'osama',
 'party',
 'patient',
 'peace',
 'policies',
 'policy',
 'president',
 'presidential',
 'primaries',
 'primary',
 'prize',
 'process',
 'promoted',
 'proposition',
 'protection',
 'raise',
 'reauthorization',
 'receive',
 'received',
 'recession',
 'recovery',
 'reelected',
 'referred',
 'reform',
 'regained',
 'reinvestment',
 'related',
 'relations',
 'relief',
 'repeal',
 'represent',
 'representatives',
 'representing',
 'republican',
 'republicans',
 'response',
 'resulted',
 'review',
 'rights',
 'rodham',
 'romney',
 'running',
 'russia',
 'sandy',
 'school',
 'seats',
 'second',
 'senate',
 'served',
 'shooting',
 'signed',
 'sought',
 'spending',
 'start',
 'state',
 'states',
 'stimulus',
 'street',
 'strike',
 'sufficient',
 'supreme',
 'sworn',
 'taught',
 'tax',
 'taxpayer',
 'tell',
 'term',
 'terms',
 'total',
 'treaty',
 'troop',
 'unconstitutional',
 'unemployment',
 'united',
 'university',
 'unsuccessfully',
 'urged',
 'victory',
 'wall',
 'war',
 'withdrawal',
 'won',
 'worked',
 'years']

In [23]:
# Create a series from the sparse matrix
obama_counter = pd.Series(count_matrix.toarray().flatten(), 
              index = features).sort_values(ascending=False)

In [24]:
obama_counter

obama         9
act           8
law           6
military      4
control       4
             ..
normalize     1
nomination    1
nobel         1
new           1
13th          1
Length: 229, dtype: int64

# Compute TF-IDF for the entire corpus of articles

In [25]:
people['word_count']= [Counter(x) for x in people['text'].str.split()]

In [26]:
people

,name,text,word_count
0,Digby Morrell,digby morrell born 10 october 1979 is a former...,"{'digby': 1, 'morrell': 5, 'born': 1, '10': 1,..."
1,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...,"{'alfred': 1, 'j': 1, 'lewy': 3, 'aka': 1, 'sa..."
2,Harpdog Brown,harpdog brown is a singer and harmonica player...,"{'harpdog': 2, 'brown': 2, 'is': 7, 'a': 7, 's..."
3,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...,"{'franz': 1, 'rottensteiner': 3, 'born': 1, 'i..."
4,G-Enka,henry krvits born 30 december 1974 in tallinn ...,"{'henry': 1, 'krvits': 1, 'born': 1, '30': 1, ..."
...,...,...,...
59066,Olari Elts,olari elts born april 27 1971 in tallinn eston...,"{'olari': 2, 'elts': 3, 'born': 1, 'april': 1,..."
59067,Scott F. Crago,scott francis crago born july 26 1963 twin bro...,"{'scott': 1, 'francis': 1, 'crago': 5, 'born':..."
59068,David Cass (footballer),david william royce cass born 27 march 1962 in...,"{'david': 1, 'william': 1, 'royce': 1, 'cass':..."
59069,Keith Elias,keith hector elias born february 3 1972 in lac...,"{'keith': 1, 'hector': 1, 'elias': 4, 'born': ..."
59070,Fawaz Damrah,fawaz mohammed damrah arabic fawwz damra was t...,"{'fawaz': 1, 'mohammed': 1, 'damrah': 4, 'arab..."

In [27]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
tfidf_vec = TfidfVectorizer()
transformed = tfidf_vec.fit_transform(raw_documents=people['text'])
index_value={i[1]:i[0] for i in tfidf_vec.vocabulary_.items()}

In [29]:
fully_indexed = []
for row in transformed:
    fully_indexed.append({index_value[column]:value for (column,value) in zip(row.indices,row.data)})

In [30]:
people['tf_idf'] = fully_indexed

In [31]:
people

,name,text,word_count,tf_idf
0,Digby Morrell,digby morrell born 10 october 1979 is a former...,"{'digby': 1, 'morrell': 5, 'born': 1, '10': 1,...","{'melbourne': 0.04943650649482413, 'college': ..."
1,Alfred J. Lewy,alfred j lewy aka sandy lewy graduated from un...,"{'alfred': 1, 'j': 1, 'lewy': 3, 'aka': 1, 'sa...","{'every': 0.03831773682944378, 'capsule': 0.07..."
2,Harpdog Brown,harpdog brown is a singer and harmonica player...,"{'harpdog': 2, 'brown': 2, 'is': 7, 'a': 7, 's...","{'society': 0.03991955990922275, 'hamilton': 0..."
3,Franz Rottensteiner,franz rottensteiner born in waidmannsfeld lowe...,"{'franz': 1, 'rottensteiner': 3, 'born': 1, 'i...","{'kurdlawitzpreis': 0.08928312306619517, 'spec..."
4,G-Enka,henry krvits born 30 december 1974 in tallinn ...,"{'henry': 1, 'krvits': 1, 'born': 1, '30': 1, ...","{'curtis': 0.052582727709648204, 'promo': 0.06..."
...,...,...,...,...
59066,Olari Elts,olari elts born april 27 1971 in tallinn eston...,"{'olari': 2, 'elts': 3, 'born': 1, 'april': 1,...","{'ivth': 0.09848761070515089, 'orchestraolaris..."
59067,Scott F. Crago,scott francis crago born july 26 1963 twin bro...,"{'scott': 1, 'francis': 1, 'crago': 5, 'born':...","{'cosongwriting': 0.08387253596002299, 'sounda..."
59068,David Cass (footballer),david william royce cass born 27 march 1962 in...,"{'david': 1, 'william': 1, 'royce': 1, 'cass':...","{'grewcock': 0.12163141646353066, '15696': 0.1..."
59069,Keith Elias,keith hector elias born february 3 1972 in lac...,"{'keith': 1, 'hector': 1, 'elias': 4, 'born': ...","{'recordselias': 0.1249798907183773, 'cochampi..."
59070,Fawaz Damrah,fawaz mohammed damrah arabic fawwz damra was t...,"{'fawaz': 1, 'mohammed': 1, 'damrah': 4, 'arab...","{'trusteesdue': 0.12446926794278577, 'damra': ..."

## Examine the TF-IDF for the Obama article

In [32]:
obama = people[people['name'] == 'Barack Obama']
#obama[['tf_idf']].stack('tf_idf',columns=['word','tf_idf']).sort('tf_idf',ascending=False)

In [33]:
obama

,name,text,word_count,tf_idf
35817,Barack Obama,barack hussein obama ii brk husen bm born augu...,"{'barack': 1, 'hussein': 1, 'obama': 9, 'ii': ...","{'2012obama': 0.07885433263257774, 'doddfrank'..."

In [75]:
obama_tf = pd.DataFrame(obama['tf_idf'].iloc[0].items(), columns=['Word', 'tf_idf'])

In [76]:
obama_tf = obama_tf.sort_values('tf_idf', ascending=False)

In [77]:
obama_tf

      Word    tf_idf
98   obama  0.365018
266    the  0.279323
92     act  0.249089
264     in  0.209673
114   iraq  0.151809
..     ...       ...
268     is  0.014350
216    new  0.013177
221  which  0.012341
232   that  0.011600
256     by  0.009598

[270 rows x 2 columns]

## Examine the TF-IDF for Clooney

In [96]:
clooney = people[people['name'] == 'George Clooney']

In [97]:
clooney

,name,text,word_count,tf_idf
38514,George Clooney,george timothy clooney born may 6 1961 is an a...,"{'george': 1, 'timothy': 1, 'clooney': 4, 'bor...","{'categoriesclooney': 0.10120408406633526, 'he..."

In [98]:
clooney_tf = pd.DataFrame(clooney['tf_idf'].iloc[0].items(), columns=['Word', 'tf_idf'])

In [99]:
clooney_tf

                  Word    tf_idf
0    categoriesclooney  0.101204
1               heslov  0.101204
2     producingclooney  0.101204
3              syriana  0.089978
4         leatherheads  0.094993
..                 ...       ...
231                the  0.313680
232               with  0.043103
233                who  0.017115
234                 is  0.046044
235               born  0.011365

[236 rows x 2 columns]

In [100]:
clooney_tf = clooney_tf.sort_values('tf_idf', ascending=False)

In [101]:
clooney_tf

         Word    tf_idf
231       the  0.313680
30    clooney  0.307745
42   thriller  0.211806
58      drama  0.157204
65      actor  0.141867
..        ...       ...
180  american  0.019064
233       who  0.017115
211      from  0.011594
235      born  0.011365
225       was  0.009673

[236 rows x 2 columns]